site_name: Lzh's Blog
site_url: null
site_description: Lzh's Blog
site_author: zhl
copyright: "Copyright © 2019 - 2023 Lzh's Blog 许可协议:CC BY-SA 4.0"

nav:
  - index.md
  - "2023":
    - "04":
      - 2023/04/1.md
    - "03":
      - 2023/03/2.md
      - 2023/03/1.md
    - "02":
      - 2023/02/5.md
      - 2023/02/4.md
      - 2023/02/3.md
      - 2023/02/2.md
      - 2023/02/1.md
    - "01":
      - 2023/01/3.md
      - 2023/01/2.md
      - 2023/01/1.md

extra:
  disqus: 'someting'
  generator: false
  copyright: '<a href="https://creativecommons.org/licenses/by-sa/4.0/deed.zh">CC BY-SA 4.0</a> 和 <a href="https://github.com/zTrix/sata-license">SATA</a>'
  pagetime: 'on'
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/liuzihaohao
      name: Github
    - icon: fontawesome/brands/slack
      link: https://liuzihaohao.github.io
      name: Blog
    - icon: fontawesome/solid/paper-plane
      link: 2629827923@qq.com
      name: E-mail

features:
  - navigation.top

theme:
  name: material
  language: 'zh'
  palette:
    - primary: 'green'
    - accent: 'green'
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  include_search_page: false
  search_index_only: true
  favicon: 'icon.ico'
  icon:
    logo: 'material/school'
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
    - navigation.tabs
    - navigation.instant
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'

  favicon: 'icon.png'

  language: 'zh'

# Extensions
markdown_extensions:
  - admonition
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: ""
      slugify: !!python/name:pymdownx.slugs.uslugify
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences

extra_javascript:
  - '/static/js/MathJax.js'

