site_name: Lzh's Blog
site_url: null
site_description: Lzh's Blog
site_author: lzh
copyright: "Copyright &copy; 2019 - 2024 Lzh's Blog 许可协议: CC BY-NC-ND 4.0"

nav:
  - index.md
  - "2024":
    - "02":
      - blog/2024/02/2.md
      - blog/2024/02/1.md
  - "2023":
    - "12":
      - blog/2023/12/1.md
    - "07":
      - blog/2023/07/1.md
    - "06":
      - blog/2023/06/1.md
    - "05":
      - blog/2023/05/2.md
      - blog/2023/05/1.md
    - "04":
      - blog/2023/04/7.md
      - blog/2023/04/6.md
      - blog/2023/04/5.md
      - blog/2023/04/4.md
      - blog/2023/04/3.md
      - blog/2023/04/2.md
      - blog/2023/04/1.md
    - "03":
      - blog/2023/03/2.md
      - blog/2023/03/1.md
    - "02":
      - blog/2023/02/5.md
      - blog/2023/02/4.md
      - blog/2023/02/3.md
      - blog/2023/02/2.md
      - blog/2023/02/1.md
    - "01":
      - blog/2023/01/3.md
      - blog/2023/01/2.md
      - blog/2023/01/1.md

extra:
  disqus: 'someting'
  generator: false
  copyright: '<a href="https://creativecommons.org/licenses/by-nc-nd/4.0/">CC BY-NC-ND 4.0</a>'
  pagetime: 'on'
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/liuzihaohao
      name: Github
    - icon: fontawesome/brands/slack
      link: https://liuzihaohao.github.io
      name: Blog
    - icon: fontawesome/solid/paper-plane
      link: liuzihao_lzh@hotmail.com
      name: E-mail

features:
  - navigation.top

theme:
  name: material
  language: 'zh'
  palette:
    - primary: 'green'
    - accent: 'green'
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  include_search_page: false
  search_index_only: true
  favicon: 'icon.ico'
  icon:
    logo: 'material/school'
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
    - navigation.tabs
    # - navigation.instant # 瞬间加载
    # 代码块
    - content.code.copy
    # - content.code.annotate 

    #- navigation.instant # 点击内部链接时，不用全部刷新页面
    - navigation.tracking # 在url中使用标题定位锚点
    - navigation.tabs # 顶部显示导航顶层nav（也就是第一个节点）
    - navigation.tabs.sticky # 滚动是隐藏顶部nav，需要配合navigation.tabs使用
    - navigation.sections # nav节点缩进
    # - navigation.expand # 不折叠左侧nav节点
    - navigation.indexes # 指定节点index pages ，跟instant不兼容
    - toc.integrate # 右侧生产目录
    - navigation.top # 一键回顶部
    - header.autohide
  custom_dir: overrides  # 自定义主题设置。overrides目录与docs目录同级
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'

  favicon: 'icon.png'

  language: 'zh'

# Extensions
markdown_extensions:
  # 术语提示
  - abbr
  - pymdownx.snippets
  # 提示 警告框
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  # 按钮
  - attr_list
  # 代码块
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  # 内容标签页
  - pymdownx.tabbed:
      alternate_style: true
  
  - tables # 表格
  - footnotes # 注脚

  # 格式化处理
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

  # 图片
  - attr_list
  - md_in_html

  # 列表
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  
  # emoji
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  
  - meta # metadata
  - toc:
      permalink: ""
      slugify: !!python/name:pymdownx.slugs.uslugify
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.magiclink # 自动识别链接
  - pymdownx.progressbar
  - pymdownx.smartsymbols # 智能符号

extra_javascript:
  - javascripts/extra.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js

extra_css:
    - stylesheets/extra.css

plugins:
  - git-revision-date-localized:
      type: datetime
      custom_format: "%d. %B %Y"
      timezone: Asia/Shanghai
      locale: ZH
      # fallback_to_build_date: false
      enable_creation_date: true
      exclude:
          - index.md
      enabled: true
      strict: true
  - tags
